### ISSUE TITLE
Hey?

### ISSUE THREAD

**Issue by LankyBox01** [Semisol/Semisol#2]
Hello. this is the only way i could contact you :/
Do you want to help me with something?

**Comment by LankyBox01** [comment]
> You can go to [`Semisol/Semisol`](https://github.com/Semisol/Semisol) to contact me there with an issue.

So, the project was actually delayed. BUT, for now, can you make an account [here](https://techhelp.flarum.cloud/)?
We will discuss it there

**Comment by LankyBox01** [comment]
also, i'm turkish too :)

**Comment by Semisol** [comment]
ok @LankyBox01

**Comment by Semisol** [comment]
So? @LankyBox01

**Comment by Semisol** [comment]
so????? @LankyBox01 i dont understand

**Comment by LankyBox01** [comment]
...a month later

**Comment by Semisol** [comment]
yes

**Comment by Semisol** [comment]
i just am closing issues that arent needed
